# Site settings
title: Thomas Stapleton
email: tstapleton@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learning by doing. Forever a student. The personal website for Thomas Stapleton.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tstapleton.github.io/" # the base hostname & protocol for your site
twitter_username: thomasstapleton
github_username: tstapleton
linkedin_username: thomasstapleton

# Build settings
markdown: kramdown
highlighter: pygments

kramdown:
  input: GFM
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: true

  coderay:
    coderay_wrap: div
    coderay_line_numbers: table
    coderay_line_number_start: 1
    coderay_tab_width: 2
    coderay_bold_every: false
    coderay_css: class

tag_page_layout: tag_page
tag_page_dir: tags
tag_permalink_style: pretty

collections:
  styletiles:
    output: true
    permalink: /styletiles/:path/
  projects:
    output: true
    permalink: /projects/:path/
